### ISSUE TITLE
[mail] Problem with ThingActions

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#8204]
After updating from OpenHAB 2.5.6 to 2.5.7 sending of mails isn't working again. Within the OpenHAB log I see many of these errors: "2020-07-26 13:17:05.598 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'Trockner fertig': 'sendMail' is not a member of 'org.eclipse.smarthome.core.thing.binding.ThingActions'; line 64, column 5, length 136".

I found some old discussions with the same error messages and the "solution"/workaround seems to restart OpenHAB multiple times... It seems to be a random initialization error within the mail binding. That should get fixed because it is very annoying when an update of OpenHAB isn't working.

Old discussions:
- https://community.openhab.org/t/solved-mail-binding-issue-again/90791
- https://community.openhab.org/t/sendmail-not-working-2-5-0-m2/80041
- https://community.openhab.org/t/solved-i-having-trouble-new-mail-binding/88203
- https://community.openhab.org/t/mail-binding-2-5-1-error/91193/5

**Comment by J-N-K** [comment]
There have been fixes in 2.5.7 to workaround this issue. The code that produces this error is no longer part of the codebase, so this results from old code and an old bundle lingering around somewhere. Restarting once (if possible cleaning cache) should fix this.

**Comment by Novanic** [comment]
> There have been fixes in 2.5.7 to workaround this issue. The code that produces this error is no longer part of the codebase, so this results from old code and an old bundle lingering around somewhere. Restarting once (if possible cleaning cache) should fix this.

But the error occurred in 2.5.7?! I see this error in 2.5.7 after from 2.5.6, so I would think it wasn't fixed successfully.

**Comment by J-N-K** [comment]
As I said: the 2.5.6 bundle seems to be in cache or memory. It‘s impossible that the 2.5.7 bundle creates this error. The message has been completely removed.

**Comment by Novanic** [comment]
@J-N-K Hm, the error occurred 2 days after updating and I think I had already restarted it after the update to 2.5.7. But ok, I have restarted again and will open a new issue when it occurs again.
