### ISSUE TITLE
[Tellstick] Addon not working with the latest builds

### ISSUE THREAD

**Issue by oklona** [openhab/openhab-addons#7024]
When installing version 2.5.x of "release" versions of OpenHAB, the Tellstick binding does not work.

Using clean Docker containers, I see two different issues currently (version 2.5.1):

- The binding complains that Telldus Core library is not installed. This library is quite outdated, and relies on some old Linux libraries that are currently hard to get a hold of. Following recipes on the net, I was able to install it.
- The next issue is that the binding cannot initialize because of missing functionality in io.netty.handler.ssl.JdkSslContext. According to the logs, to me it looks like the JdkSslContext handler either expects a list of supported ciphers as an input, or receives an unexpected list of supported ciphers? Of course, their server only support outdated SSL 3.0 and TLS 1.0, and only old, insecure ciphers.

Here is the error message from openhab.log:

[ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.tellstick.internal.live.TelldusLiveBridgeHandler@16ae8aca': io/netty/handler/ssl/JdkSslContext
java.lang.NoClassDefFoundError: io/netty/handler/ssl/JdkSslContext
        at io.netty.handler.ssl.NettySslPackageAccessor.jdkSupportedCipherSuites(NettySslPackageAccessor.java:24) ~[?:?]

## Expected Behavior
The binding initializes properly, and the Telldus.Net bridge comes online.
## Current Behavior
In current releases, the Telldus.Net bridge Thing does not come online, but remains in an uninitialized state.

## Possible Solution
I have no good solution to suggest, but the binding works in my "production" 2.5.0 M3 installation.

## Steps to Reproduce (for Bugs)
1. Install OpenHAB
2. Add the Tellstick binding (I have used Paper UI for this)
3. Configure the binding with a Telldus Live account. (I believe you can create an account for free at live.telldus.com in case you do not have one.), using API credentials retrieved from api.telldus.com.

## Context
The binding is not working, blocking me from upgrading to the current release. I would like to upgrade, to take advantage of new versions of other bindings.

## Your Environment
Official OpenHAB Docker container, running on Ubuntu 18.04 on Intel x86-64 hardware.

**Comment by oklona** [comment]
I contacted Telldus regarding the fact that api.telldus.com does not support higher TLS versions than TLS 1.0, and they responded that api.telldus.com will be turned off soon, and we were recommended to use pa-api.telldus.com instead. I don't know if this is already known by those who maintain this binding, so thought it would be useful to add it here.

**Comment by flippz** [comment]
> I contacted Telldus regarding the fact that api.telldus.com does not support higher TLS versions than TLS 1.0, and they responded that api.telldus.com will be turned off soon, and we were recommended to use pa-api.telldus.com instead. I don't know if this is already known by those who maintain this binding, so thought it would be useful to add it here.

Adding that url in Zway (alternative to openhab) works fine... Although the default api.telldus.com works aswell there...

**Comment by kalleboll** [comment]
I ran into this problem myself as well when I tried to upgrade from OpenHab 2.4 to 2.5 before and now when I tried to upgrade to 3.0.
As it was not being fixed I decided to give it a go myself and this will be my first contribution to the OpenHab project. 

The problem was caused by the asynchttpclient dependency that seemed to require another version of the Netty dependency than what is added by the openhab.tp-netty feature.
This caused some of the classes in the ssl package to not be found during initialization.
I fixed it by upgrading the asynchttpclient dependency to a version that use the same version of Netty that is bundled(4.1.42.Final).
It fixed the problem for me at least but I only have Telldus switches so I can't test it out for dimmers or sensors.
The PR is currently in review.

**Comment by oklona** [comment]
Perfect, thanks! I tried looking into this, but as the whole Java / Maven approach is something I know little about, I couldn't fix it without spending more time than I had available. I am quite sure a lot of Tellstick users are very happy to have this fixed! In the meantime, I have moved to a different approach, running a Docker container, which in turn runs a Python script to interact with my Tellstick.Net locally (without depending on Telldus Live) through MQTT. 

In the past, Telldus has been one of the bindings that has more often than not caused errors when upgrading OpenHAB, and as I only use it to collect data from Oregon sensors, and controlling Christmas lights, it is a relief to have it separate from my main OpenHAB :-)
