### ISSUE TITLE
[telegram] Binding stopped working after upgrade to openhab 5

### ISSUE THREAD

**Issue by brainbug95** [openhab/openhab-addons#19234]
Hi everyone,

since the upgrade from openhab 4.x to 5.0.1 I have an issue with my existing rules using the telegram binding. 

This is my rule: I am using "telegramAction.sendTelegramPhoto" as documented here: https://www.openhab.org/addons/bindings/telegram/
```
/* Doorbell actions */
rule "Doorbell"
when
  Channel 'homematic:HM-Sen-DB-PCB:ccu2:IDIDIDID:1#BUTTON' triggered SHORT_PRESSED
  or
  Item TelegramTest1 changed to ON
then
  logInfo("surveillance.rules", "Somebody rang the doorbell.")
  val telegramAction = getActions("telegram","telegram:telegramBot:botId")
  telegramAction.sendTelegramPhoto("http://cam-url/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=000000&user=someone&password=somepass", "Es hat an der Tür geklingelt!\n")
end
```

After the upgrade it stopped working and only logs an error:

```
==> /var/log/openhab/openhab.log <==
2025-08-23 20:20:31.614 [INFO ] [core.model.script.surveillance.rules] - Somebody rang the doorbell.
2025-08-23 20:20:31.616 [ERROR] [.handler.AbstractScriptModuleHandler] - Script execution of rule with UID 'surveillance-4' failed: 'sendTelegramPhoto' is not a member of 'org.openhab.core.thing.binding.ThingActions'; line 42, column 3, length 184 in surveillance
```

Can anyone elaborate on what is suddenly wrong with my rule?

Thanks in advance,
Christian

**Comment by brainbug95** [comment]
I think this issue should be moved to https://github.com/openhab/openhab-addons. My mistake.

**Comment by lsiepel** [comment]
Have the binding in daily use without issues. Just not using this specific call. https://github.com/openhab/openhab-addons/pull/17801/ introduced a updated lib. Might have broken this specific call. Will test later today.

**Comment by brainbug95** [comment]
@lsiepel I changed the action to "telegramAction.sendTelegram". I am getting the same error. Here is the full DSL rule:

```
/* Doorbell actions */
rule "Doorbell"
when
  Channel 'homematic:HM-Sen-DB-PCB:ccu2:IDIDIDID:1#BUTTON' triggered SHORT_PRESSED
  or
  Item TelegramTest1 received update ON
then
  logInfo("surveillance.rules", "Somebody rang the doorbell.")
  val telegramAction = getActions("telegram","telegram:telegramBot:botid")
  telegramAction.sendTelegram("Es hat an der Tür geklingelt!\n")
end
```

I tried manually sending a telegram message via UI which worked so I think something changed in the way the DSL rule must be written and the documentation was not updated or it is a bug.

**Comment by lsiepel** [comment]
Your rule exactly looks like mine.
You probably did the obvious checks, restart openHAB. send a "hello world" message without special characters or ü etc. 

Sorry to say, but i cannot reproduce or spot the issue. As the action in the UI works, it does not seem to be a binding issue. very strange though.

**Comment by brainbug95** [comment]
Yes, I did all that. I tried sending a picture without caption at all. I tried changing the text to a simple string like "test". I uninstalled and installed the telegram binding. No luck.

I copied my rule in the UI and edited the copy to do the same except not using "inline script" and it worked:

```
configuration: {}
triggers:
  - id: "0"
    configuration:
      event: SHORT_PRESSED
      channelUID: homematic:HM-Sen-DB-PCB:ccu2:IDIDIDID:1#BUTTON
    type: core.ChannelEventTrigger
  - id: "1"
    configuration:
      itemName: TelegramTest1
      state: ON
    type: core.ItemStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "3"
    configuration:
      config: telegram:telegramBot:botId
      photoURL: http://cam-url/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=000000&user=none&password=home
      caption: Es hat an der Tür geklingelt!
    type: telegram.sendTelegramPhoto#somehashid

```

Unfortunately this is only possible for these very simple rules. Most of my other rules involving telegramAction are much more complex.

Is there anything I can deliver to help debugging the issue further?

**Comment by lsiepel** [comment]
Maybe @rkoshak can be of any help here?

**Comment by rkoshak** [comment]
I can't help a whole lot but I do know that if the Thing is not online, `getActions("telegram","telegram:telegramBot:botid")` will return `null`. That's the first thing I would check. The binding might have other cases where it returns `null` or something other than an Object with the right `methods`.

**Comment by pzelensky** [comment]
Did anyone found any workaround for this issue?

**Comment by lsiepel** [comment]
> Did anyone found any workaround for this issue?

No, as it does not seem to be reproducible on my side all works as expected.

**Comment by brainbug95** [comment]
It is very strange, but I noticed my original rules started working again. I think after I upgraded my k3s setup which is running on the same node but kubernetes is only handling  ingress for openhab. I do not think that it is related in anyway but in the process I had to reboot the whole system. But I rebooted many times before as well so I do not think that's related either. Anyhow the error is gone and i cannot reproduce it anymore. 

Sorry for the inconvenience as it obviously had something to do with my setup.

**Comment by lsiepel** [comment]
@pzelensky what about the issues you have? Anything in the logs, rebooted the system? any usefull leads ?

**Comment by pzelensky** [comment]
@lsiepel exact the same message in the logs. DSL rule configured with the file doesn't work.
the same rule created with UI works as expected. But huh, I have plenty of rules in files, git repo with them, versioning etc. Not a great idea moving them to UI.

**Comment by lsiepel** [comment]
I'm clueless to why this fails in DSL rule file and works in UI.
I can't reproduce it.

Same openHAB version, same binding version. Same rule. Maybe some other binding interfering? Are you able to test with a fresh openHAB download and just this binding + rules? And from there add the other bindingsd you have?

**Comment by lsiepel** [comment]
If you put the binding in trace mode logging , does that give any leads?

**Comment by jba3001** [comment]
I have the same problem after each update and restart.
Sorry, but can't get the debug from a fresh installation, but maybe the log from the last startup may help:

[log_telegram.txt](https://github.com/user-attachments/files/23167948/log_telegram.txt)

**Comment by igorky** [comment]
I have the same issue after upgrading to the 5.0.2.

`[ERROR] [.handler.AbstractScriptModuleHandler] - Script execution of rule with UID 'telegram-1' failed: 'sendTelegram' is not a member of 'org.openhab.core.thing.binding.ThingActions';`

All my rules are in the `/etc/openhab/rules`.

I can send telegram messages from UI through Thing -> Actions -> send a message.

**Comment by lsiepel** [comment]
Anyone able to test if this also happens when using another file based script engine like ecmascript or other.

Can you share the installed bundles by an export of the karaf console `bundle:list`
Would also be appreciated if you can provide a regular openHAB log from boot until the script is triggered.

**Comment by catalinsanda** [comment]
I also have a similar issue after upgrading to 5.0.3. This code which was working:
```
        val mailActions = getActions("mail", "mail:smtp:mailserver")
        val boolean success = mailActions.sendMail("some.email@gmail.com", "Openhab is alive", "Test email")
```
not fails with:
```
2025-11-29 20:11:03.963 [ERROR] [.handler.AbstractScriptModuleHandler] - Script execution of rule with UID 'alerts-6' failed: 'sendMail' is not a member of 'org.openhab.core.thing.binding.ThingActions'; line 127, column 24, length 81 in alerts
```

I can also send emails by invoking the Thing from the UI.

In my logs I find a lot of errors when starting up OpenHAB, which might be related.

```
2025-11-29 20:26:49.517 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'hue-remote-terrace-awning.rules'
2025-11-29 20:26:49.625 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR
java.lang.IllegalStateException: Invalid class loader from a refreshed bundle is being used: org.openhab.core.model.rule_5.0.3
        at org.eclipse.osgi.internal.loader.BundleLoader.getProviderLoader(BundleLoader.java:1011) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findRequiredSource(BundleLoader.java:1246) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:490) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168) ~[org.eclipse.osgi-3.18.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at org.openhab.core.model.script.scoping.ActionClassLoader.loadClass(ActionClassLoader.java:34) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:536) ~[?:?]
        at java.lang.Class.forName(Class.java:515) ~[?:?]
        at org.eclipse.xtext.common.types.access.impl.ClassFinder.forName(ClassFinder.java:42) ~[?:?]
        at org.eclipse.xtext.common.types.access.impl.ClassFinder.forName(ClassFinder.java:1) ~[?:?]
        at org.eclipse.xtext.common.types.access.impl.AbstractClassFinder.forName(AbstractClassFinder.java:44) ~[?:?]
        at org.eclipse.xtext.common.types.access.reflect.ReflectionTypeProvider.findTypeByName(ReflectionTypeProvider.java:87) ~[?:?]
        at org.eclipse.xtext.common.types.util.TypeReferences.findDeclaredType(TypeReferences.java:256) ~[?:?]
        at org.eclipse.xtext.common.types.util.TypeReferences.findDeclaredType(TypeReferences.java:233) ~[?:?]
        at org.eclipse.xtext.xbase.jvmmodel.JvmTypeReferenceBuilder.typeRef(JvmTypeReferenceBuilder.java:66) ~[?:?]
        at org.openhab.core.model.rule.jvmmodel.RulesJvmModelInferrer.lambda$7(RulesJvmModelInferrer.java:180) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.openhab.core.model.rule.jvmmodel.RulesJvmModelInferrer.lambda$0(RulesJvmModelInferrer.java:186) ~[?:?]
        at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator$1.run(JvmModelAssociator.java:398) ~[?:?]
        at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:408) ~[?:?]
        at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:244) ~[?:?]
        at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:149) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:284) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:108) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.checkPath(FolderObserver.java:285) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.processIgnoredPaths(FolderObserver.java:194) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.addModelParser(FolderObserver.java:103) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:245) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:687) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:531) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BindMethod.invoke(BindMethod.java:42) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2086) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2061) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:336) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:304) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1232) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1152) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:959) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:895) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1184) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:116) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:123) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:961) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:937) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:874) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:262) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:500) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:929) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:915) ~[?:?]
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:984) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1274) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1225) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1232) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1152) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:959) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:895) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1184) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:116) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:123) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:961) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:937) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:874) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:262) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:500) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:929) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:915) ~[?:?]
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:984) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437) ~[?:?]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:671) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:310) ~[?:?]
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:593) ~[?:?]
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:74) ~[?:?]
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:460) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488) ~[osgi.core-8.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420) ~[osgi.core-8.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[osgi.core-8.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[osgi.core-8.0.0.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:949) [org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:499) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.Module.start(Module.java:486) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.ModuleContainer.start(ModuleContainer.java:888) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:879) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:560) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:503) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1139) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1520) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi-3.18.0.jar:?]
```

**Comment by lsiepel** [comment]
Did you get this sorted?
If not, try upgrading to 5.1.0, let it run for a bit, and reboot.

**Comment by catalinsanda** [comment]
Yes. Recreating the container and deleting the volumes solved the problem.

**Comment by lsiepel** [comment]
What about @igorky and @jba3001 ?

**Comment by jba3001** [comment]
> What about [@igorky](https://github.com/igorky) and [@jba3001](https://github.com/jba3001) ?

Everything is fine for me. No error messages and Telegrams are sent.
Thx!

**Comment by lsiepel** [comment]
As all seems sorted I close this.
